### PR TITLE
git ignore custom mods/themes; fix check duplicate kill

### PR DESCRIPTION
**Pull request by 6RUN0**
I run script
<code>$php cron_zkb.php</code>
and get error:
Database error: Duplicate entry '34873218' for key 'kll_external_id'
SQL: UPDATE kb3_kills JOIN kb3_mails ON kb3_mails.kll_id = kb3_kills.kll_id SET kb3_kills.kll_external_id = 34873218, kb3_mails.kll_external_id = 34873218, kll_modified_time = UTC_TIMESTAMP() WHERE kb3_kills.kll_id = 32730 AND kb3_kills.kll_external_id IS NULL
PHP Fatal error:  SQL error (Duplicate entry '34873218' for key 'kll_external_id' in /home/u5577/domains/insp.su/killboard/common/includes/class.dbnormalquery.php on line 46

This patch fix problem.

### CODE REVIEW

**Comment by Salvoxia** [comment]
Hi,

thanks for the patch!. 
This could only happen if there there is already a kill with that very same external ID, but another internal ID (so presumably another hash), so something must be corrupt there (or they would have the same hash and therefore only one kill would exist).
Because of that I'm somewhat reluctant to merge this patch, but I guess it makes sense regarding the robustness of zKB Fetch.

BTW: I assume this is the kill it tried to verify? http://insp.su/killboard/?a=kill_detail&kll_id=32730
The API verified mod shows "verified", but there's no external ID. And if you try to view that kill with that external ID, you get an error: http://insp.su/killboard/?a=kill_detail&kll_ext_id=34873218
So I guess there IS something wrong :)

Regards,
Salvoxia

**Comment by 6RUN0** [comment]
``` mysql
select * from kb3_kills where kll_external_id='34873218'\G
*************************** 1. row ***************************
kll_id: 204
kll_timestamp: 2013-11-30 00:48:00
kll_victim_id: 332
kll_all_id: 1
kll_crp_id: 40
kll_ship_id: 0
kll_system_id: 30000317
kll_fb_plt_id: 333
kll_points: 0
kll_dmgtaken: 12527
kll_external_id: 34873218
kll_isk_loss: 0
```

``` mysql
select * from kb3_kills where kll_id='32730'\G
*************************** 1. row ***************************
kll_id: 32730
kll_timestamp: 2013-11-30 00:48:00
kll_victim_id: 332
kll_all_id: 1
kll_crp_id: 40
kll_ship_id: 33474
kll_system_id: 30000317
kll_fb_plt_id: 333
kll_points: 240
kll_dmgtaken: 12527
kll_external_id: NULL
kll_isk_loss: 800000
```

http://insp.su/killboard/?a=kill_detail&kll_id=204

Such situation could occur if the not actual version of a killboards was used.

**Comment by 6RUN0** [comment]
If disable realmoney_mod then `curl -I http://insp.su/killboard/?a=kill_detail&kll_ext_id=34873218` return HTTP 200OK

**Comment by 6RUN0** [comment]
I patched realmoney_mod.
Commands:
`curl -I "http://insp.su/killboard/?a=kill_detail&kll_ext_id=34873218"`
&&
`curl -I "http://insp.su/killboard/?a=kill_detail&kll_id=204"`
return HTTP 200OK

**Pull request closed without merging**
