### PR TITLE
Feature: Add Redis cache system based on memcache handler + Error handler modification

### PR DESCRIPTION
**Pull request by hjf288**
This is a very simple Redis cache handler based on the memcache handler as an alternative to the memcached caching.

Also PHP errors should only be displayed on the frontend if the user has `display_errors` on, this adds a conditional to check.

### CODE REVIEW

**Comment by Salvoxia** [comment]
Hi,

great, thank you for your contribution!
I'll give it some testing and merge it into the dev branch if everything is fine.

Regards,
Salvoxia

**Comment by Salvoxia** [comment]
Hi,

I did some testing and there's one thing that I noticed: If the Redis server is not available once Redis caching has been activated, the killboard fails to load anything with the error "Redis server has gone away". 
It should revert to a fallback without redis chaching instead (like it does if memcache caching is activated, but the connection to memcached fails).
Could you add that?

Best Regards,
Salvoxia

**Comment by hjf288** [comment]
Latest commit should resolve that.

**Comment by Salvoxia** [comment]
Hi,

it seems https://github.com/hjf288/evedev-kb/commit/6476237ebd0ac78ad687d99f59547dd8fee16e8e does not quite work es expected: pconnect() seems to throw a RedisException if it can't connect, that exceptions needs to be caught. 

Best Regards,
Salvoxia

edit: nvm, my fault ;)

**Comment by hjf288** [comment]
What PHP version are you testing with as I shutdown my Redis server during testing?

**Comment by Salvoxia** [comment]
Never mind my last comment, I made a mistake while testing.
Works as exepcted. :+1:

**Pull request merged**
